In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 

In [4]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[['Frace' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [21]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [22]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 2:4])
X[:, 2:4] = imputer.transform(X[:, 2:4])

In [23]:
print(X)

[['Frace' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X[:, :-1]))

In [25]:
print(X)

[[1.0 0.0 0.0 0.0 44.0]
 [0.0 0.0 0.0 1.0 27.0]
 [0.0 0.0 1.0 0.0 30.0]
 [0.0 0.0 0.0 1.0 38.0]
 [0.0 0.0 1.0 0.0 40.0]
 [0.0 1.0 0.0 0.0 35.0]
 [0.0 0.0 0.0 1.0 nan]
 [0.0 1.0 0.0 0.0 48.0]
 [0.0 0.0 1.0 0.0 50.0]
 [0.0 1.0 0.0 0.0 37.0]]


In [26]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [27]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [29]:
print(X_train)

[[0.0 0.0 0.0 1.0 nan]
 [0.0 0.0 1.0 0.0 40.0]
 [1.0 0.0 0.0 0.0 44.0]
 [0.0 0.0 0.0 1.0 38.0]
 [0.0 0.0 0.0 1.0 27.0]
 [0.0 1.0 0.0 0.0 48.0]
 [0.0 0.0 1.0 0.0 50.0]
 [0.0 1.0 0.0 0.0 35.0]]


In [30]:
print(X_test)

[[0.0 0.0 1.0 0.0 30.0]
 [0.0 1.0 0.0 0.0 37.0]]


In [31]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [32]:
print(y_test)

[0 1]


In [33]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [34]:
print(X_train)

[[0.0 0.0 0.0 1.2909944487358056 nan]
 [0.0 0.0 1.0 -0.7745966692414834 -0.038910211282047996]
 [1.0 0.0 0.0 -0.7745966692414834 0.5058327466666259]
 [0.0 0.0 0.0 1.2909944487358056 -0.3112816902563849]
 [0.0 0.0 0.0 1.2909944487358056 -1.809324824615238]
 [0.0 1.0 0.0 -0.7745966692414834 1.0505757046152997]
 [0.0 0.0 1.0 -0.7745966692414834 1.3229471835896367]
 [0.0 1.0 0.0 -0.7745966692414834 -0.7198389087178904]]


In [35]:
print(X_test)

[[0.0 0.0 1.0 -0.7745966692414834 -1.4007676061537326]
 [0.0 1.0 0.0 -0.7745966692414834 -0.4474674297435534]]
